server:
  port: 8081
  servlet:
    context-path: /demo
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://60.205.189.104:3306/db0926?useSSL=false
    username: db001
    password: ysdss1991
